### ISSUE TITLE
Unobtainable/difficult additional hearthfire dolls

### ISSUE THREAD

**Issue by Hukkatsu** [Lost-Outpost/lost-legacy#103]
2 hearthfire dolls are difficult to obtain and 1 is impossible.
Ebony doll (impossible)- Buried underground at last sigil due to a conflict with Ryn's snazzy last sigil editing the worldspace.
Recommended solution:
Edit FE063838 BYOHEbonyDoll tamriel block 1, -1 sub-block 5, -3
X: 196144
Y: -73397
Z: 15805
Note: This solution will only affect new saves (why I'm posting this now). It will place it on the ground outside the door to last vigil keep. You can test it quickly by setting your own position there on a new character.

Markarth guard doll- Buried in a stone bed in Markarth guard barracks (right side bedroom, 2nd bed on the right). It is obtainable with some destruction spells like tri-disaster or twisting tempest to fling it somewhere else in the room. I was unable to get it with unrelenting force.
Recommended solution:
Should be fixed in Legacy of the Dragonborn Patches (Official) 2.9.6. Recommend checking when testing 1.2. If not, slightly increasing its Z value should work.

Dragon plate doll-  Mostly inside of an urn on a table in the first room of Labyrinthian. It can be obtained by approaching the urn from the back and trying to grab the doll from different angles.
Recommended solution:
Should be fixed in Legacy of the Dragonborn Patches (Official) 2.9.6. Recommend checking when testing 1.2. If not, slightly changing it's X and Y should work.

**Comment by GreatPadinski** [comment]
Should be fixed in 1.2.0
