### ISSUE TITLE
Vahlok not dropping mask

### ISSUE THREAD

**Issue by Hukkatsu** [Lost-Outpost/lost-legacy#105]
Dragon priest vahlok had a mask added in LotD. This mask is placed as part of his outfit and, according to the wiki, meant to drop from him.

Recommended solution-
I was unable to figure out how LotD is supposed to get the mask to drop. The best I can come up with is to set Vahlok's 'Use Inventory' flag to null and add it as an item in his inventory in LostLegacy_RealBosses-KA.esp. This drops the mask while retaining the cursed vahlok's robes, cursed vahlok's gauntlets, and cursed vahlok's greaves drops. Vahlok does not have an amulet or ring drop so no need to worry about those.

Mask- 09166B5A DBM_VahlokMask
Outfit- 090610EB DBM_VahlokOutfit
Vahlok- 0401CAD5 DLC2SV01DragonPriestBoss

![image](https://github.com/Lost-Outpost/lost-legacy/assets/135540947/c35de9a9-80c8-4674-87c2-b194b1e52b46)

**Comment by GreatPadinski** [comment]
Should be fixed in 1.2.0
