### ISSUE TITLE
Wabbajack keeps failing to download LostLegacy_DynDOLOD_Output_1.1.0.7z

### ISSUE THREAD

**Issue by Dormdude** [Lost-Outpost/lost-legacy#106]
As the title says. Can I get a direct link? Thanks

**Comment by selsie** [comment]
You could have just used Google to find this page:
https://build.wabbajack.org/authored_files
and this link:

https://authored-files.wabbajack.org/LostLegacy_DynDOLOD_Output_1.1.0.7z_47a1835f-9072-41aa-a23d-87fabb6ee0d6

**Comment by Dormdude** [comment]
I searched around but couldn't find it. Thanks.
