### ISSUE TITLE
Game goes off monitor at 21:9 and 16:9 resolutions

### ISSUE THREAD

**Issue by Dormdude** [Lost-Outpost/lost-legacy#107]
I have a 2560x180 monitor. The resolution is set correct in MO2 inis. I have the optional 21:9 fixes turned on. But the games stretches well off my monitor both horizontally and vertically. I've tried everything I can think of. I've messed with the with the fulllscreen and borderless settings, I've tried disabling the 21:9 fixes, I've tried flawless widescreen fix which works for fallout 4, I've even tried setting it just to normal 16:9, it still stretches off my screen vertically. I have never seen this issue before modding skyrim, and as far as I can find in my searches nobody else has had this issue with skyrim ever. I'm open to any suggestions.

**Comment by selsie** [comment]
You need to right click on the skyrim.exe and go to "Properties" and then find the DPI settings. Set them to be controlled by the application.

**Comment by Dormdude** [comment]
> You need to right click on the skyrim.exe and go to "Properties" and then find the DPI settings. Set them to be controlled by the application.

Sadly didn't do it for me. I did it for both the Stock Game and my Steam Common folders for skyrim, just in case. I tried messing with some of the other dpi settings and even made sure it's set to run as administrator too.

**Comment by selsie** [comment]
Don't do it for the folder. And NEVER run a file as administrator, unless you need to.
There is another question for that, including answer. Please check the closed issues, and you'll find it.

**Comment by Dormdude** [comment]
Which folder are you referring to? I tried the dpi setting in either and both. I only turned it on run as administrator as a test to see if it would fix, thanks for the info I won't use it again. I'm not really sure which issue thread you are referring too.

**Comment by selsie** [comment]
There is a link in the last post. Leading directly to the answer

**Comment by Dormdude** [comment]
Well I gave up after nothing else worked. I deleted the modlist and decided to just use the downloaded mods in my own list
