### ISSUE TITLE
Keyboard layout menu origin or how to disable?

### ISSUE THREAD

**Issue by Ralkero** [Lost-Outpost/lost-legacy#114]
I just installed Lost Legacy, can someone tell me which mod adds the keyboard layout menu that comes up when I press X? I want to rebind it but I can't figure out where that option is. [Screenshot here.](https://i.imgur.com/xsAqBs6.jpeg)

**Comment by GreatPadinski** [comment]
I think we got this sorted out in discord a while back? If not, just reopen this and I can assist.
