### ISSUE TITLE
[Castlevania - Vampire Killer] should be updated to last version.

### ISSUE THREAD

**Issue by EdualcLaiv** [Lost-Outpost/lost-legacy#118]
The version of Castlevania - Vampire Killer (1.1)  used in Lost Legacy 1.1.1 supposedly fixed an issue breaking ambient music. It actually didn't, but it should be sorted since 1.3.

Could you update it for Lost Legacy 1.2?
I saw you've made some patches for this mod, so I don't know how complicated/long/annoying updating it woud be and if those patches need to be redone.

**Comment by GreatPadinski** [comment]
Updated for 1.2, thanks!
