### ISSUE TITLE
BETA: Report minor issues here!

### ISSUE THREAD

**Issue by GreatPadinski** [Lost-Outpost/lost-legacy#119]
Please use this post to report minor issues for the 1.2.0 beta. Things like clipping objects, landscape seams, or anything that isn't a major issue like crashing or broken features.

Be sure to include the exact location, console click on the object and include a screenshot with all of that info if possible.

**Comment by Muew19** [comment]
![image](https://github.com/Lost-Outpost/lost-legacy/assets/138997808/8e7e67be-92d9-45da-b5c5-ac2e628eb876)
Winterhold Carriage unclickable missing landscape

**Comment by monkeyangst** [comment]
Using a controller, and QuickLoot doesn't always want to recognize the A button. Sometimes it works immediately, sometimes there's a delay, and sometimes it just doesn't work at all. X button and D-pad work OK though.

**Comment by StrangelyShapedCorndog** [comment]
chapter II - soundtrack mod by dreyma music esp from optionals isp laced below the map .esps at the bottom of the load order. Not sure if intentional.

**Comment by espii94** [comment]
Just encountered a bug, I just entered whiterun for the first time, and Anoriath was hostile and attacked me immediatly on sight.
I have reloaded a save now two times that is just before I got to whiterun, and everytime I get to the market area he becomes hostile for some reason.

**Comment by GreatPadinski** [comment]
> 

Can you please attach a save file so  I can check it out?

**Comment by GreatPadinski** [comment]
> Just encountered a bug, I just entered whiterun for the first time, and Anoriath was hostile and attacked me immediatly on sight. I have reloaded a save now two times that is just before I got to whiterun, and everytime I get to the market area he becomes hostile for some reason.

Can you please attach a save file so I can check it out? @espii94

**Comment by espii94** [comment]
> > Just encountered a bug, I just entered whiterun for the first time, and Anoriath was hostile and attacked me immediatly on sight. I have reloaded a save now two times that is just before I got to whiterun, and everytime I get to the market area he becomes hostile for some reason.
> 
> Can you please attach a save file so I can check it out? @espii94

I am trying, but I just get a message that the file type isn't supported so I can't upload it, am I doing something wrong? Sorry, Github is completely new for me haha

**Comment by GreatPadinski** [comment]
> > > Just encountered a bug, I just entered whiterun for the first time, and Anoriath was hostile and attacked me immediatly on sight. I have reloaded a save now two times that is just before I got to whiterun, and everytime I get to the market area he becomes hostile for some reason.
> > 
> > 
> > Can you please attach a save file so I can check it out? @espii94
> 
> I am trying, but I just get a message that the file type isn't supported so I can't upload it, am I doing something wrong? Sorry, Github is completely new for me haha

You can just toss it in discord and @ me then lol @espii94

**Comment by StrangelyShapedCorndog** [comment]
bound whip spell is invisible. Attack animations are still there tho, with visuals. Invisible in 3rd and 1st person. My pictures are too big to upload :(. "bound whip dual" is also invisible. IDs for the spells are bound whip: 7431bdb6 and bound whip dual: 7431bdb7.

**Comment by EdualcLaiv** [comment]
Floating mushrooms.
![image](https://github.com/Lost-Outpost/lost-legacy/assets/4270058/3d34562c-4441-403a-a205-b87e19c63242)
![image](https://github.com/Lost-Outpost/lost-legacy/assets/4270058/bb09dc56-7ca4-4937-b396-5a37e55a0e5b)

**Comment by GreatPadinski** [comment]
From James: "Check the LostLegacy-MerchantContainers.esp for the MErchantCaravanA B and C chest? I am showing an error on the last item in them."

**Comment by GreatPadinski** [comment]
From Matt: Arrows glitching in and out when holding a bow

**Comment by CrazyDiamond567** [comment]
![JackTheRipper](https://github.com/Lost-Outpost/lost-legacy/assets/25443922/a9a27715-fdfa-4983-ada1-2d7a92770634)
![Location](https://github.com/Lost-Outpost/lost-legacy/assets/25443922/e242d626-56e1-4301-b570-48b8b56c0377)

Jack the Ripper is attacking Midwood isle NPC's in what I think is the travel point for that mod.

**Comment by Mindrix** [comment]
Some weird texture nonsense in the Bard's College.

As seen below, some textures seem to change to darker variation for some reason when I look at them. (Pointing the crosshair at them)

![20230711172116_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/505c94b4-ef97-4107-aea3-0a3d5be0b9b1)
![20230711172118_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/faac3705-4648-4a70-8ce5-dfe2526e9dbf)
![20230711172125_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/1cf84a88-7a9a-41a9-bab0-4dd834b10757)
![20230711172128_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/4cfa56ec-bdba-4c55-b502-7125e1b63914)
![20230711172140_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/973f64e3-aa50-480d-952e-eebc4c397b6f)
![20230711172141_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/615858df-bacb-4436-a4eb-83949aab2bd8)
![20230711172157_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/a4334df6-76ff-4e74-8321-a2810eb0c9cf)
![20230711172158_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/46465b72-82c8-4a38-9814-db5f0dda3874)
![20230711172641_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/b509f7f2-a9f2-43aa-8814-faedf60ea86a)
![20230711172642_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/a1f0178c-5ff4-4c9b-afaa-e13a78b07dc7)

**Comment by sorenvalen** [comment]
![image](https://github.com/Lost-Outpost/lost-legacy/assets/101903326/f8870e39-528f-4581-8872-6d9ed2dac011)
would this count as minor of major basiclly bortherhood of old is unfinshable when you supsoe to go defeat the torg ppl in the save basiclly there is a texsute blocking the entrace since this is a scriped seen where hes supsoe to come out i can cheat my way in there since he need to come outside

**Comment by GreatPadinski** [comment]
> Some weird texture nonsense in the Bard's College.
> 
> As seen below, some textures seem to change to darker variation for some reason when I look at them in a certain way.
> 
> ![20230711172116_1](https://user-images.githubusercontent.com/46691946/252809109-505c94b4-ef97-4107-aea3-0a3d5be0b9b1.jpg) ![20230711172118_1](https://user-images.githubusercontent.com/46691946/252809111-faac3705-4648-4a70-8ce5-dfe2526e9dbf.jpg) ![20230711172125_1](https://user-images.githubusercontent.com/46691946/252809112-1cf84a88-7a9a-41a9-bab0-4dd834b10757.jpg) ![20230711172128_1](https://user-images.githubusercontent.com/46691946/252809113-4cfa56ec-bdba-4c55-b502-7125e1b63914.jpg) ![20230711172140_1](https://user-images.githubusercontent.com/46691946/252809114-973f64e3-aa50-480d-952e-eebc4c397b6f.jpg) ![20230711172141_1](https://user-images.githubusercontent.com/46691946/252809116-615858df-bacb-4436-a4eb-83949aab2bd8.jpg) ![20230711172157_1](https://user-images.githubusercontent.com/46691946/252809117-a4334df6-76ff-4e74-8321-a2810eb0c9cf.jpg) ![20230711172158_1](https://user-images.githubusercontent.com/46691946/252809118-46465b72-82c8-4a38-9814-db5f0dda3874.jpg) ![20230711172641_1](https://user-images.githubusercontent.com/46691946/252809119-b509f7f2-a9f2-43aa-8814-faedf60ea86a.jpg) ![20230711172642_1](https://user-images.githubusercontent.com/46691946/252809121-a1f0178c-5ff4-4c9b-afaa-e13a78b07dc7.jpg)

That's just a lighting bug unfortunately, nothing I can really do about it

**Comment by Muew19** [comment]
![image](https://github.com/Lost-Outpost/lost-legacy/assets/138997808/ed605728-ec80-4d5c-abfb-21361a1e2899)
Missing Shrine of Azura

**Comment by GreatPadinski** [comment]
> ![image](https://user-images.githubusercontent.com/138997808/253200897-ed605728-ec80-4d5c-abfb-21361a1e2899.png) Missing Shrine of Azura

Where exactly is this? Can you post a screenshot of your map, or open console and hit tab until it shows the cell info in the top right?

**Comment by Muew19** [comment]
Its at the actual big shrine between winterhold and windhelm, not at home now to show id.

**Comment by GreatPadinski** [comment]
> Its at the actual big shrine between winterhold and windhelm, not at home now to show id.

That works, I'll check it out. Thanks!

**Comment by Mindrix** [comment]
1st Issue: Missing wall corners in the Bard's College, top floor.

![20230713152732_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/789ae856-e23c-4478-aab4-d60ca99aed51)
![20230713152740_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/43489196-1b2f-4300-8e4e-b94b106eb63f)

2nd Issue: Mazha's work does not seem to be present or loaded in.

![20230713152903_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/72ab23ce-3f95-4eeb-adb2-6d02d2c109fb)

**Comment by GreatPadinski** [comment]
> ![image](https://user-images.githubusercontent.com/138997808/253200897-ed605728-ec80-4d5c-abfb-21361a1e2899.png) Missing Shrine of Azura

So the giant statue is gone for you? Seems to be fine for me:
![Screenshot510](https://github.com/Lost-Outpost/lost-legacy/assets/96201854/a7420dca-2344-4a22-a190-b428aa38cc9d)

**Comment by Mindrix** [comment]
Colorful Magic adds _another_ always hostile boss on a random road, this time on the road between Falkreath and Helgen.

Also right near the spot that you start the hang-glider quest. 

![20230713171632_1](https://github.com/Lost-Outpost/lost-legacy/assets/46691946/d739e503-c3af-4f2d-97d3-ebc20b5b22d0)

**Comment by Muew19** [comment]
> > ![image](https://user-images.githubusercontent.com/138997808/253200897-ed605728-ec80-4d5c-abfb-21361a1e2899.png) Missing Shrine of Azura
> 
> So the giant statue is gone for you? Seems to be fine for me: ![Screenshot510](https://user-images.githubusercontent.com/96201854/253410580-a7420dca-2344-4a22-a190-b428aa38cc9d.png)

My bad I actually thought there's supposed to be a small altar on there cuz theres an activate button on the table for shrine of azura and the candles seemed weirdly placed so thought a smaller shrine is missing like those of the aedra in towns below the big statues

**Comment by Fsusilo** [comment]
This is more like a comment than a report but, is it possible to make Colorful Magic mod optional only? The mod is really unbalanced. Some bosses are really broken and OP, Some spell are OP as well and as well as their armor.

**Comment by Mindrix** [comment]
It seems that the Real Names mod keeps automatically applying to some of the Colorful Magic bosses.

**Comment by sorenvalen** [comment]
i chim this is a general skyrim jank bug not something the mod list creator can recarte if npc agro you you can type in console tdetect then setav aggression 0 make sure on both of the commands a listed you have the npc selceted

**Comment by EdualcLaiv** [comment]
Objects like fences (mainly but not limited to) disapearing/flickering at Falkreath when approached from a precise angle.
https://youtu.be/4jG7OoRDYXo
Near the East gate.

**Comment by GreatPadinski** [comment]
> Objects like fences (mainly but not limited to) disapearing/flickering at Falkreath when approached from a precise angle. https://youtu.be/4jG7OoRDYXo Near the East gate. ![image](https://user-images.githubusercontent.com/4270058/254406710-1a0ef031-6397-4eaa-bf8b-68c13fbf5963.png)

That's just an occlusion culling plane, they're not perfect but help with fps.

**Comment by EdualcLaiv** [comment]
Olava the Feeble is naked (except the fur collar).
![image](https://github.com/Lost-Outpost/lost-legacy/assets/4270058/0269fc1a-a2e8-403f-8c2f-399830a3e527)
(Nope, I didn't mess with Simple Outfit System)

**Comment by Juniper8961** [comment]
General Store sells nothing. Most recent Beta from yesterday. BETA 4
![enb2023_7_19_15_21_17](https://github.com/Lost-Outpost/lost-legacy/assets/139983319/3e9cc145-2bde-4846-b368-ba7f0580c0d8)
![enb2023_7_19_15_21_59](https://github.com/Lost-Outpost/lost-legacy/assets/139983319/adf89ca9-ddac-40b0-91ed-e90abb6f990d)

**Comment by Juniper8961** [comment]
These two in the Markarth outskirts are naked. Most recent Beta 4.
![enb2023_7_19_15_38_38-min](https://github.com/Lost-Outpost/lost-legacy/assets/139983319/e66f4a01-d36c-4d11-84cc-be4c89ac5566)

![enb2023_7_19_15_38_31-min](https://github.com/Lost-Outpost/lost-legacy/assets/139983319/5e73a7ee-d9bf-4b35-b391-6da05bfe9bff)

**Comment by Juniper8961** [comment]
Potato Plants almost entirely dissapear when approached in Markarth outskirts. Most recent Beta4
![enb2023_7_19_15_42_32-min](https://github.com/Lost-Outpost/lost-legacy/assets/139983319/5fa99228-cfcb-401d-9117-e9ddd8fc4558)
![enb2023_7_19_15_42_40-min](https://github.com/Lost-Outpost/lost-legacy/assets/139983319/408b20bf-2f4b-4c6e-83f4-dbab8e639a4a)

**Comment by Juniper8961** [comment]
Massive culling issues in markarth Outskirts. Looking from one of the little watchtowers.
![enb2023_7_19_16_05_40-min](https://github.com/Lost-Outpost/lost-legacy/assets/139983319/612ab1b3-06c0-4710-90b0-9dd8115769c5)
![enb2023_7_19_16_06_00-min](https://github.com/Lost-Outpost/lost-legacy/assets/139983319/c63e6bf7-8646-4362-9743-94485058aa16)
![enb2023_7_19_16_06_15-min](https://github.com/Lost-Outpost/lost-legacy/assets/139983319/04c35998-66d4-4979-a630-51bc648254ce)

**Comment by bernasx** [comment]
Version: Beta 4

Buyable Home Patch for Elysium Estate SSE is not working. You do the Elysium Estate quest by talking to the ghost and then the Shrine, but when you go to Honningbrew Meadery, Sabjorn does not sell the key as intended.

It is possible Mallus sells it once you advanced in the Thieves Guild questline, but the mod page says both should sell it depending on their status.

Can ping me on Discord (bernas) if you need more details or a save file.

**Comment by Owlgamer6** [comment]
Tree clipping though a house
![enb2023_7_26_19_59_16](https://github.com/Lost-Outpost/lost-legacy/assets/140340846/5eed76c9-523f-41f2-9d3e-cb44bee75894)
![enb2023_7_26_20_01_08](https://github.com/Lost-Outpost/lost-legacy/assets/140340846/c0ecacda-3c84-4077-918a-8b49f203081d)

**Comment by hterez** [comment]
![20230727202957_1](https://github.com/Lost-Outpost/lost-legacy/assets/110639292/cf7664bc-c038-474d-838d-26e34ea79e1f)

Book of Koridai spawns outside of the accessible world in Mistviel Keep, which I discovered when Schneider's Sextant put a marker on it

**Comment by Owlgamer6** [comment]
Floating letter from relics of hyrule in warmaidens, in Whiterun
![enb2023_8_4_22_43_18](https://github.com/Lost-Outpost/lost-legacy/assets/140340846/023a45c2-01db-4c88-8ca7-b8de7eacc19d)

**Comment by Owlgamer6** [comment]
Random thing in the air over the whiterun area
![enb2023_8_6_16_18_43](https://github.com/Lost-Outpost/lost-legacy/assets/140340846/747bd121-a441-4de7-aa5b-5fdf9d6f1956)
![enb2023_8_6_16_18_53](https://github.com/Lost-Outpost/lost-legacy/assets/140340846/f1005a4f-e0cd-498e-b685-174db7ee1c0b)
