### ISSUE TITLE
can i update betas mid palythough 

### ISSUE THREAD

**Issue by sorenvalen** [Lost-Outpost/lost-legacy#120]
is the betas okay to update mid palythough without a new save i figure beta 3 is coming out tonight orr tomrrow and i am on beta 1 right now i wanted to know if the beta patches so far are save safe

**Comment by GreatPadinski** [comment]
Yeah so far the Betas have been save safe with eachother. Still not 100% sure on if Beta > full 1.2.0 will be save safe though.

**Comment by sorenvalen** [comment]
thanks for the info
