### ISSUE TITLE
default start - prisoner cart missing 

### ISSUE THREAD

**Issue by Rhyvon55** [Lost-Outpost/lost-legacy#122]
If you pick the default start, where you would go to the porch of the inn and watch the prisoner cart roll in  - the cart, prisoners are all missing. the horse that pulls the cart walks in alone.

**Comment by GreatPadinski** [comment]
Hah! I'll have to give it a test and see if I get the same thing. Are you playing the 1.2.0 beta or are you on 1.1?

**Comment by Rhyvon55** [comment]
1.2 beta Sent from my T-Mobile 5G Device
-------- Original message --------From: GreatPadinski ***@***.***> Date: 7/11/23  8:49 AM  (GMT-07:00) To: Lost-Outpost/lost-legacy ***@***.***> Cc: Rhyvon55 ***@***.***>, Author ***@***.***> Subject: Re: [Lost-Outpost/lost-legacy] default start - prisoner cart missing 
  (Issue #122) 
Hah! I'll have to give it a test and see if I get the same thing. Are you playing the 1.2.0 beta or are you on 1.1?

**Comment by GreatPadinski** [comment]
Tested several times, couldn't reproduce the issue. No changes have been made to that mod, so I'm guessing it's just a random one-off

**Comment by Rhyvon55** [comment]
Glad to hear it! Love your mod pack.Sent from my T-Mobile 5G Device
-------- Original message --------From: GreatPadinski ***@***.***> Date: 7/11/23  9:20 PM  (GMT-07:00) To: Lost-Outpost/lost-legacy ***@***.***> Cc: Rhyvon55 ***@***.***>, Author ***@***.***> Subject: Re: [Lost-Outpost/lost-legacy] default start - prisoner cart missing 
  (Issue #122) 
Tested several times, couldn't reproduce the issue. No changes have been made to that mod, so I'm guessing it's just a random one-off
