### ISSUE TITLE
cant finsh bothoerhood of old

### ISSUE THREAD

**Issue by sorenvalen** [Lost-Outpost/lost-legacy#123]
![image](https://github.com/Lost-Outpost/lost-legacy/assets/101903326/080da01e-357d-4c11-bb68-7420a4be7e9f)
terrain blocked i  i got the mesh that sticking though it in the picutre with the base id

**Comment by sorenvalen** [comment]
in this srcipted sceen emieny are sumspeo to walk out so this mesh needs to be remove is block all progress

**Comment by GreatPadinski** [comment]
Looked at it for a while and ended up just removing Krovaxis for 1.2.0 so this is fixed

**Comment by sorenvalen** [comment]
hey remember the last time i tryed to reprot this i think it was when the bortherhood of old was put in as a mod i could not print seen back then it was aveing my print sceen where i could not post it i had to find it in lost legacy and load them before looks like reinstilling windows did fix that issue or the keybind optional

**Comment by sorenvalen** [comment]
![image](https://github.com/Lost-Outpost/lost-legacy/assets/101903326/f97aa386-d75b-4d50-a8e6-8a24a7f8e04c)
it look like they both use the exate same world space

**Comment by sorenvalen** [comment]
i had no clue witch mod was conrfixing so i could not look it up

**Comment by GreatPadinski** [comment]
It was in the bottom left of your screenshot btw
