### ISSUE TITLE
Third person archery/magic crosshair is constantly askew

### ISSUE THREAD

**Issue by TheDarkLxrd** [Lost-Outpost/lost-legacy#125]
I like to play in 3rd person most of the time but I can't really use a bow or magic effectively at all. I have my cross hair set to where it is always showing, and when I draw my bow, the line of fire is always like a full inch to the left and down a bit from my cross hair on my screen. Same with magic. That's where my arrows and magic shoot every time. Never in the center. When aiming the trajectory of the arrow at an object in front of me, the further away the object is, the closer the trajectory gets to the center of the screen. So it makes it basically impossible to use bows and hard to use magic in 3rd person having to constantly compensate and aim to the left. It should be noted that when you look straight up into the sky or at something thats too far away for an arrow trajectory, the trajectory disappears and the centered cross hair reappears. This makes it ridiculously hard to hit moving targets ok top of a hill, for example, because you can't see a trajectory until you line the target up in this weird spot a little to the left and down of the crosshair. So annoying. I just wanna play the game in third person. I'll provide a picture or two. I'm really hoping you can fix this for 1.2, or at least provide me with a solution, as I am hoping you have seen this problem or ran into it before. I know I can't be the only one with this problem, as it has done this since the first time I drew a bow the first time I launched the game. I tried messing with SmoothCam cross hair settings and with the archery overhaul in the mcms to no avail. Thanks for your time. Hope this helps.

By the way in the pictures I'm providing, you can see what I mean. My camera/crosshair is aimed at exactly the same spot. I did not move it at all before drawing my bow. Yet I aim at the tree for some reason.

![16893268253908431202193255539744](https://github.com/Lost-Outpost/lost-legacy/assets/139544803/24bacc87-b5bb-4624-bcdd-399543dc14a0)

![1689326872032547000941098426442](https://github.com/Lost-Outpost/lost-legacy/assets/139544803/e46eaf9d-9914-4584-bad0-6af582c7d427)

**Comment by GreatPadinski** [comment]
Honestly have no idea, I don't seem to have an issue. I saw someone mentioned this mod recently in the discord, could give that a shot https://www.nexusmods.com/skyrimspecialedition/mods/18524
