### ISSUE TITLE
1.2 - Improved Camera SE needs to be updated to work with Switch Camera During Dialogue

### ISSUE THREAD

**Issue by EdualcLaiv** [Lost-Outpost/lost-legacy#130]
**Improved Camera SE** needs to be updated to last version (1.0.3), or enabling it will break **Switch Camera During Dialogue** (going from 3rd person to 1st during dialogue works fine, but not the other way around)

- Note that current profiles in `SKSE\Plugins\ImprovedCameraSE\Profiles\` seems to be incompatible with the latest update. 
  Some of your tweaks must be redone, like but probably not limited to: 
  - First person bow makes the arrow flicker.
    -  Archery Gameplay Overhaul in Fixes.
  - Zoom key not working.
    - Disabling FOV Overide.

PS: could you please tell me which are the other customizations you made in Improved Camera SE? I'm trying to redo them after updating it in my game and it still feels different somehow.

**Comment by GreatPadinski** [comment]
I'll update it for 1.2.1, thanks! And I think those were the only 2 settings. It should pull in from the profile though, unless updating it changed the default profile (which is the most likely cause) 
![image](https://github.com/Lost-Outpost/lost-legacy/assets/96201854/88620e99-3feb-4182-804f-5b7337f1a5d5)
