### ISSUE TITLE
Thieves Guild Shill Jobs not working

### ISSUE THREAD

**Issue by Rpn145** [Lost-Outpost/lost-legacy#132]
The shill jobs in the thieves guild give you a stolen gem or jewelry piece and tell you to put it in a chest of a npc's house, but the quests are incompletable. If i were to speculate it would be because Better Stealing might be flagging them as no longer stolen and therefore a different item when you place it in the chest, but that might be baseless.

**Comment by GreatPadinski** [comment]
I'll test it out and see if I can get the same issue.
