### ISSUE TITLE
[Addition Request for 1.2.1] GORE - Miscellaneous Patches - SDA Patch

### ISSUE THREAD

**Issue by EdualcLaiv** [Lost-Outpost/lost-legacy#133]
Hello,

There is now a "GORE - Serana Dialogue Add-On Patch" on "GORE - Miscellaneous Patches" files tab.
https://www.nexusmods.com/skyrimspecialedition/mods/94223

I guess you'll probably want to add it to your to-do list for 1.2.1.

**Comment by GreatPadinski** [comment]
Added to my list, thanks!
