### ISSUE TITLE
Lost legacy modlist won't let me start Dragonborn DLC

### ISSUE THREAD

**Issue by discowizzy** [Lost-Outpost/lost-legacy#134]
No other mods added, all mods that are currently enable by default are enabled, and yet the dragonborn DLC doesn't organically start no matter what I try. I've used console commands to try and start it, but I can't get the cultists to come organically, and even with commands, it takes a lot of work to make the Dragonborn DLC main quest function. 

Not sure what other information to add, let me know.

**Comment by GreatPadinski** [comment]
The cultist attack is delayed via Timing is Everything. I'm not in-game to check the exact requirements, but I think you have to be level 25 and you have to complete some of the main quest as well. But if you go in game and check the Timing is Everything MCM, you should see the requirements in there.

**Comment by sorenvalen** [comment]
you need to comaple horn of jurgan and be 25 i think its ether way of the vocie of the horn of jargeren windcaller as the quest but you need acess to a upgaruded forodah
