### ISSUE TITLE
Deep Elf Perk Problem

### ISSUE THREAD

**Issue by PhantomHatter** [Lost-Outpost/lost-legacy#135]
So Deep Elf's starting perk for Dwarven smithing is kinda misleading. It states you can make Dwarven armor at the start of the game. This isn't true however since you still need the perk Ancient Knowledge to access base Dwarven armor and weapons to make at a smithy. I see two ways to fix it from my opinion, one maybe unbalanced, the other to keep it how it is, Either remove the perk (so ancient knowledge is still required to be able to make regular Dwarven armor and weapons) or the Deep Elf race can start with Ancient Knowledge to reflect the race. Either way the only reason I'm suggesting this is I was extremely confused by the wording and thought my game was bugged or that it wasn't possible.

**Comment by Mixplit74** [comment]
I also ran into this issue and had to dig through the discord for a fix.  One more thing I can add, this also prevents you from taking the Meric smithing perk for Dwarven items as the game shows you already having it. Making it harder for a Deep Elf to smith Dwarven items than any other race. The only fixes being to do the quest Unfathomable Depths or use the console to add the Ancient Knowledge perk.

**Comment by GreatPadinski** [comment]
Yeah I'll look into adding that perk to the race as well.
