### ISSUE TITLE
Skulltula spiders spawning in falkreath taverns.

### ISSUE THREAD

**Issue by NomadsReach** [Lost-Outpost/lost-legacy#138]
Hello, as you can see from the title I am having them spawn in adnormal areas.  Please see link below from discord for images.

![](https://cdn.discordapp.com/attachments/909669255367233586/1149987351431495762/image.png)

![](https://cdn.discordapp.com/attachments/909669255367233586/1149987351943192646/image.png)

**Comment by NomadsReach** [comment]
![image](https://github.com/Lost-Outpost/lost-legacy/assets/144523850/13864752-c8cb-4390-9d4d-afab30bef83f)

**Comment by GreatPadinski** [comment]
That's odd, but also kind of hilarious lol. I'll see if I can reproduce it, but you're the first to report it so I'm hoping it's just a weird one-off.
