### ISSUE TITLE
sneak function not working

### ISSUE THREAD

**Issue by bcalvo1** [Lost-Outpost/lost-legacy#142]
no matter the input device, wether you press the sneak button or hold it the character does a silent roll instead of sneaking. I have checked the mapping, restarted the game and computer, any recomondations would be helpful

**Comment by GreatPadinski** [comment]
Press C for sneak. Ctrl is dodge. Also hit F11 to see the list of keybinds
in game.

**Comment by bcalvo1** [comment]
![image](https://github.com/Lost-Outpost/lost-legacy/assets/70531512/51e3b417-fdf9-437e-bbe2-a361ece8d034)
it is mapped correctly

**Comment by sorenvalen** [comment]
To change the key back change the the sneak in menus to something like caps lock then go into ultimate dogge to I think crit key this is I think how mine is set up there are vary few reasons to ever toggle run off
