### ISSUE TITLE
Game breaking bug

### ISSUE THREAD

**Issue by SurgeO2** [Lost-Outpost/lost-legacy#143]
After the dragon rises main quest, right after bleak falls barrows, After talking to Jarl Balgruuf when Irileth goes downstairs, Player freezes, not the game. Just the player. Its so odd, never seen it before. cant move, cant look around. It happens right after it says "Jarl Balgruuf is now my confidant"

**Comment by GreatPadinski** [comment]
It's a bug with the gore mod. Fix will be included in the next update, but you can fix it quick by doing this:
![image](https://github.com/Lost-Outpost/lost-legacy/assets/96201854/ffad76fc-f543-4931-a5cf-f8ec5fef6f60)
