### ISSUE TITLE
Crashes on starting a new game

### ISSUE THREAD

**Issue by appelofdoom** [Lost-Outpost/lost-legacy#145]
The title screen has texture issues as the icon is purple (common sign of missing textures) and there's no transparency to the fog and when starting a new game the alduin model in the first loading screen also lacks textures and the game crashes soon thereafter.

**Comment by GreatPadinski** [comment]
Sounds like your install didn't finish successfully or you're launching Skyrim via Steam. I'd rerun wabbajack to reinstall the list and make sure it's successful, then make sure you open mo2 after and launch the game via the button at the top right 
![image](https://github.com/Lost-Outpost/lost-legacy/assets/96201854/954c25b9-43af-4d74-9723-374f87f03805)
