### ISSUE TITLE
Game crashes upon entering/loading Dawnstar

### ISSUE THREAD

**Issue by Venxineythuekrop** [Lost-Outpost/lost-legacy#149]
I just started my play-through, and have not tampered with any of the mods. I attempted to take a carriage to dawnstar, but the game froze up on the loading screen. I have also tried walking there, but when I get within a certain distance the game freezes up again. This doesn’t seem to be happening with any other Holds or locations.

**Comment by joebog1** [comment]
I have the exact same issue. Something related is mentioned here: https://www.reddit.com/r/skyrimmods/comments/uf64aj/ctd_when_entering_dawnstar_anniversary_edition/?rdt=43572

Perhaps it's the same issue with the alternate start mod. I hope this gets fixed soon!

**Comment by joebog1** [comment]
It should also be mentioned if you are planning on doing falskaar you can't come back without console commands, as leaving the intended way places you in Dawnstar.

**Comment by TheOneLiliad** [comment]
Same

**Comment by GreatPadinski** [comment]
Skyrim update borked stuff. 1.2.1c is out now to fix this.
