### ISSUE TITLE
Freezing's infront of Dead Men's Respite

### ISSUE THREAD

**Issue by Owlgamer6** [Lost-Outpost/lost-legacy#150]
Going to the front of (dead men's respite) cause's my game to freeze requiring me to use task manager to stop the game, This happens on a fresh save file as well.

**Comment by joebog1** [comment]
Other places cause the game to freeze as well. The Whiterun Imperial camp is another one.

Probably all caused by the same issue?

**Comment by GreatPadinski** [comment]
Skyrim update borked stuff. 1.2.1c is out now to fix this.
