### ISSUE TITLE
Permanent Game Freeze near or at Dawnstar or Karthwasten

### ISSUE THREAD

**Issue by TheOneLiliad** [Lost-Outpost/lost-legacy#152]
Dawnstar has become more cursed than ever since every time I attempt to do literally anything including save near dawnstar the game freezes until I restart. I cannot do anything not even fast travel there or take a carriage.

Please fix this. I am using the base modlist with only performance mode turned on.

Same thing with Karthwasten

I have 32 GB RAM so memory is not the issue

**Comment by Mae197** [comment]
im having the same problem where i cant even go too far north or my entire computer freezes running with 32 gb of ram and have tried giving skyrim more ram

**Comment by GreatPadinski** [comment]
Skyrim update borked stuff. 1.2.1c is out now to fix this.
