### ISSUE TITLE
Twilight Sepulcher

### ISSUE THREAD

**Issue by TheGamingGeneral** [Lost-Outpost/lost-legacy#154]
During the quest Darkness Returns you have to follow "The Pilgrims Path" and navigate the twilight sepulcher. However part of the dungeon has a poisonous? floor that basically kills you in 2 seconds. With the ENB being dark AF in this area and the killer floor it basically makes it a nightmare to traverse without TGM. Might wanna look into tweaking that a bit.

**Comment by GreatPadinski** [comment]
Noted, will check it out
