### ISSUE TITLE
Issues with CC content

### ISSUE THREAD

**Issue by HeavyQuill** [Lost-Outpost/lost-legacy#156]
For some reason it gives me an issue where It keeps saying that the RareCurios CC content isnt able to download despite it being in the folder? Im unsure how ot proceed as this is my first time using wabbajack. I have tried the steps in troubleshooting several times and it seems to not work no matter how many times I restart wabbajack

**Comment by GreatPadinski** [comment]
Verify game files on steam, then run wabbajack again
