### ISSUE TITLE
Issue with AE content

### ISSUE THREAD

**Issue by CybernetricKat** [Lost-Outpost/lost-legacy#157]
When installing, I get an error that says "Unable to download Data_ccBGSSSE037-Curios.esl" and  "Unable to download Data_ccBGSSSE037-Curios.bsa" and it fails the installation. I've reinstalled the game, verified game files, retried the installation using install from disk and from gallery on Wabbajack. This issue is also happening to my friend.

**Comment by cooldude117123** [comment]
Running into the same problem as well, have also made sure that that file is showing up in my plugins and it is. Reinstalled, verified integrity of game files, not sure what else to try.

**Comment by Neeksman** [comment]
So what I did to get it moving along, is verify the integrity of Skyrim SE game files on steam, DO NOT START SKYRIM SE, then proceed with wabbajack, some reason it worked for me, lmk if it worked for you!

**Comment by cooldude117123** [comment]
Yep, that did it for me, thank you!

**Comment by Arkassan** [comment]
i have the same problem. but i tryed to verify multiple times i uninstalled i swaped my steam folder to two discs i even downgraded the game to 3 older versions its not able to get those .esl and .bsa 
do someone have an idea what i should do? 

greatings

02:11:13.899 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1436 total files, 1432 matching filesize
02:11:13.982 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse037-curios.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1170.0|data\ccbgssse037-curios.bsa)
02:11:13.982 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse037-curios.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1170.0|data\ccbgssse037-curios.esl)
02:11:13.982 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by EvandroPetrus** [comment]
Hey, @Arkassan. I just found out the difference. The issue is that Creation Club was just updated. Here's what you should do.

1. Downgrade skyrim to 1.6.4.0 -> https://www.youtube.com/watch?v=tk_yfbUa3eo

2. Don't launch skyrim main menu, just start Wabbajack directly.

3. Change the wabbajack mod manifest here: https://github.com/Lost-Outpost/lost-legacy/releases. **IMPORTANT: Use the version 1.2.1!!** 

4. Launch wabbajack and, on the first file input, select the manifest downloaded above.

5. Press play on wabbajack and best travels to you, soldier.

**Comment by EvandroPetrus** [comment]
@GreatPadinski, this should solve most problems related with Skyrim SE and the new CC update.

**Comment by GreatPadinski** [comment]
The list has been updated since this thread was created. For the current version you should just be able to verify game files, then launch the game once via steam so it updates the CC mods, then run wabbajack to install the list.
