### ISSUE TITLE
Save file corrupted and can't start a new game

### ISSUE THREAD

**Issue by firmbooty** [Lost-Outpost/lost-legacy#159]
I updated the modpack and now I can't play

**Comment by sorenvalen** [comment]
when you updated the mod pack make sure you have the same optionals as your old run things like volkanaotr black and all it addons can cause save currpotion if you dont enable them i had this issue today alone when i forogt to enable optionals but once enabled the right ones you save should load right

**Comment by sorenvalen** [comment]
also if you updated form versions before 1.20 then no save is save safe hit the new option but form 1.20 to the current 1.21 should be save safe
