### ISSUE TITLE
FOV

### ISSUE THREAD

**Issue by 444zuka** [Lost-Outpost/lost-legacy#163]
Hello, 
After installing and playing Lost Legacy, I couldn't keep playing because of the FOV.
I tried the console command FOV xx and to type fDefaultWorldFOV xx in the skyrim folder but didn't work.

I didn't find a mod or a settings to change that value, does someone have a solution for me please? 

Thank you for reading, 
Have a nice day,

**Comment by Polad-Javadi** [comment]
i have the same problem too, the FOV is way to small. I couldn't find a way to increase it.

**Comment by tqmcgaha** [comment]
Just in case anyone gets stuck on this (like I was) you can edit FOV by doing Left Shift + Home to open the menu for Improved Camera SE Editor. Then go View > FOV and you can changes the settings
