### ISSUE TITLE
[Skyrim SE] Unable to download Data_ccbgssse037-curios

### ISSUE THREAD

**Issue by marcosguedes** [Lost-Outpost/lost-legacy#168]
This is related to Rare Curios. I have Skyrim SE and the install failed repeatedly for these mods

```
00:00:27.161 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse037-curios.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1170.0|data\ccbgssse037-curios.bsa)
00:00:27.161 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse037-curios.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1170.0|data\ccbgssse037-curios.esl)
```

After a bit of googling I found out this was Creation Club content. I entered the Creation section and installed Rare Curios by hand and that fixed it, but I had to assume that was the issue. I planned on forking the project and updating the README to add this tidbit but I'm unsure if this is normal or intended. Can someone validate?

**Comment by cheridee** [comment]
I have the same problem, but I can't even enter the Creation Club section because of an ongoing problem with Bethesda servers.

**Comment by addiktd** [comment]
I'm having the same issue and I'm not that familiar with Creation Club. Any good DIY videos ? Thanks

**Comment by marcosguedes** [comment]
> I'm having the same issue and I'm not that familiar with Creation Club. Any good DIY videos ? Thanks

You're not familiar or you don't have access because of your copy?

Downloading it is just a few clicks away, check the first 40 seconds of this video https://youtu.be/fCb7ZPeJu80 I think you don't have to pay anything if you use Skyrim SE (I think I didn't?) despite what's shown in the video

As for adding manually, I'm not sure how and I've finished my run a week ago. Redownloading everything is a hassle. Sorry for not being able to provide any help

**Comment by addiktd** [comment]
Thank you for the reply! I’ve installed Creation kit. Can’t find how to modify the files manually, I guess I’ll read a bit more only.

as for the downgrade, it didn’t work for me. It created more error after following the steps on the other post.

**Comment by addiktd** [comment]
I was doing the Creation Hub wrong the whole time. Pretty straight forward when you open the game. I was trying to do it with the creation kit window which got me confused! Your video helped me a lot, thanks!
