### ISSUE TITLE
1.2.1d fails - unable to download data_curios

### ISSUE THREAD

**Issue by zubiall** [Lost-Outpost/lost-legacy#170]
Much like Issue #161, I was unable to progress past this point despite exhausting all options then trying everything in the thread as well.

The only solution I have found so far is using 1.2.1c and downgrading Skyrim to 1.6.1130.0.8, as per @taehoonsong recommendation. 

I have not paid for the anniversary edition. Could the latest update on Jan. 18 cause issues related to that?

**Comment by marcosguedes** [comment]
Does this help you? #168
