### ISSUE TITLE
Unable to download one or more archives

### ISSUE THREAD

**Issue by Klara2202** [Lost-Outpost/lost-legacy#172]
I keep getting the similar error, i have tired verfiying my files and the solution in #168/170 im not sure what to do now

here is my wabbajack log
[Wabbajack.current.log](https://github.com/Lost-Outpost/lost-legacy/files/14532596/Wabbajack.current.log)

**Comment by thejessmooney** [comment]
Hey, what did your ultimate solution end up being? I tried downloading the mod from creation club, and also tried verifying.
