### ISSUE TITLE
Unable to download Data_ccbgssse037-curios.esl 

### ISSUE THREAD

**Issue by Chanceofrice** [Lost-Outpost/lost-legacy#174]
New to this so it might be a problem on my end but the download stopped with this message. 
18:04:28.994 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse037-curios.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1170.0|data\ccbgssse037-curios.bsa)
18:04:28.994 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_ccbgssse037-curios.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1170.0|data\ccbgssse037-curios.esl)
18:04:28.994 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by GreatPadinski** [comment]
"Unable to download Data_ccbgssse037-curios"
Navigate to your Steam Skyrim Data folder
Within the data folder, delete the 2 curios files "ccbgssse037-curios.bsa" and "ccbgssse037-curios.esl"
Launch Skyrim through Steam and click the Creations button on the main menu
Press "o" on your keyboard to open the options menu and click "Download All owned Creation Club content" This will download the Rare Curios CC files.
Exit the game
Rerun the Wabbajack installer

If the Download All doesn't work, find the Rare Curios creation in the list and download that.

**Comment by Chanceofrice** [comment]
this seemed to work thank you.

**Comment by Luckieluuke** [comment]
This worked for me as well, thanks so much!

**Comment by HBmd1** [comment]
Hi,

got the same problem. But when i delete the files in Skyrim/data folder, Skyrim do not start. So i cant reinstall
the files. I also can´t delete the creation itself, because there is no unistall button.
Any other ideas? 

Thanks a lot, Sven

**Comment by Nicopowner** [comment]
my first thought is that you might have removed the wrong files, I have the above issue, deleted both files and everything runs fine
