### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by DoyleDeth** [Lost-Outpost/lost-legacy#175]
[Wabbajack.current.log](https://github.com/Lost-Outpost/lost-legacy/files/14976287/Wabbajack.current.log)

I set everything up correctly. Different folders as asked and it keeps giving me errors during installation. I have a purchased copy of SE.  I don't see a wabbajack option to restart the modlist. Overwrite option isn't working if that's what it is. Error Log provided.

**Comment by GreatPadinski** [comment]
"Unable to download Data_ccbgssse037-curios"
Navigate to your Steam Skyrim Data folder
Within the data folder, delete the 2 curios files "ccbgssse037-curios.bsa" and "ccbgssse037-curios.esl"
Launch Skyrim through Steam and click the Creations button on the main menu
Press "o" on your keyboard to open the options menu and click "Download All owned Creation Club content" This will download the Rare Curios CC files.
Exit the game
Rerun the Wabbajack installer

If the Download All doesn't work, find the Rare Curios creation in the list and download that.
