### ISSUE TITLE
Cannot start skse64_Loader.exe

### ISSUE THREAD

**Issue by Malatarious** [Lost-Outpost/lost-legacy#176]
Just did a fresh install of lost legacy, but whenever I try launching through the mod org I get that error above. I went and checked the location and it was in fact missing the loader for skse. I went ahead and download the 1.5.97 skse patch and added that loader and file into what was already there. Still didn't fix the issue, launched it from the skse loader I just downloaded and that actually launched the game. It came with texture bugs in the main menu and clicking play or new crashes the game. The second screenshot was after I added the skse patch myself, it didn't have loader and a couple other files originally. 

![1](https://github.com/Lost-Outpost/lost-legacy/assets/113309497/244fe507-11d0-4fd1-b349-24dbcf3c5b78)

![2](https://github.com/Lost-Outpost/lost-legacy/assets/113309497/d4573e48-21f1-44b2-8d66-b676aa2cb712)

Cheers

**Comment by Raedonias** [comment]
I have the exact same issue. You managed to fix it ?
