### ISSUE TITLE
Unable to download Rare Curios?

### ISSUE THREAD

**Issue by Kaitlynkitti** [Lost-Outpost/lost-legacy#179]
I look in my Skyrim installation and both the BSA and ESL are where they're supposed to be. Is Wabbajack attempting to download it from Nexus for some reason?
![image](https://github.com/Lost-Outpost/lost-legacy/assets/172981778/85cbb0a9-cc56-4c38-8c4d-2922cf5fde89)

**Comment by Kaitlynkitti** [comment]
I found the solution on the discord server. What you have to do is delete the BSA and ESL and manually redownload them through the creations menu.

**Comment by Mirzero** [comment]
I also encountered this on a clean Skyrim install, and had to update Creations content... which it took me a moment to figure out how to do.
I would recommend adding a section to the "Start Skyrim" part of the instructions:
In Steam, launch Skyrim SSE
In the Bethesda Launcher, click Play
In the Game main menu, go to Creations
In the Creations menu, go to Options (O, bottom center)
In the Options menu, click on Update all installed Creations
