### ISSUE TITLE
'Warden Of The Coast' bugged to hell and can't be completed.

### ISSUE THREAD

**Issue by Toddy969** [Lost-Outpost/lost-legacy#186]
I've even tried reverting to a save before I began it and disabling but the game won't start without it, is there a way to achieve this please? After two days of fighting WotC and getting to the point where it was almost zero fun with slow loading screens, packages not firing, quests not progressing etc etc. I don't even like the mod either, messes with too many of the fundamental mechanics of the game for me. I'm also dubious of mod authors who offer no 'good guy' path through a mod. It makes zero sense that the Dragonborn who has fought dragons, saved cities, rescued children and saved Tamriel to suddenly start blithely chucking people's lives away.

Many thanks

**Comment by TheOneLiliad** [comment]
I agree. The mod is a nice idea but good lord is it broken.
