### ISSUE TITLE
Enchanting table won't read my soul gems

### ISSUE THREAD

**Issue by ElisPlayz** [Lost-Outpost/lost-legacy#29]
Hello,
Enchanting using College of Winterhold's table in hall of the elements, doesn't seem to read my soul gems, when I put an enchant, it says insufficient charge, but the soul gems part is empty. Do I need one with a soul in them to enchant?

**Comment by GreatPadinski** [comment]
Yes, you need a soul in the soul gem to enchant with it. Empty soul gems do not work, think of it like an empty battery :)
