### ISSUE TITLE
Stuck in main quest during execution cutscene

### ISSUE THREAD

**Issue by obotai** [Lost-Outpost/lost-legacy#34]
I get into Helgen, talk to the innkeeper, sleep 1 hour, leave the Inn, the carriage arrive, the thief is killed by the archer, the Khajit gets out of the carriage, and then nothing more happens, the game is completely stuck. The nord is not executed, and Alduin doesn't land.
I tried by different start options (default, and other ones), but in any case, as soon as I start the main quest it is stuck at the same moment.
I didn't add any mods, only the Lost legacy modlist.

**Comment by MrFishay** [comment]
I'm also having this issue and according to the mod author of the Alternate Perspective mod, this is an issue when you don't have the correct version of Fuz Ro D-oh installed. 
I haven't yet tried updating to the current version as I'm scared of messing up the mod pack so I can't confirm if this is the issue, but in theory that should be how to solve it.

**Comment by obotai** [comment]
So I tried that, but it breaks the game: It freezes as soon as you get out of your bed. So I think I will wait for the Modlist owner to provide a proper fix.
But thanks for the hint anyway, that is probably the correct solution; there are just too many mods interacting for a fast fix, I suppose.

**Comment by GreatPadinski** [comment]
Fuz Ro D-oh is up to date, the newer versions are just for people who use the newer EXE.

But yeah, sadly the intro is buggy. The AP author has said a big update is in the works, but in the meantime here is a workaround:
Go inside the Helgen inn, behind the receptionist desk, down the stairs. Follow that path in the basement until you get to a ladder. Follow the ladder up and go outside. Once outside you should see a dragon head poking out of the hill. Talk to the dragon head and use the Teleport to Keep option to bypass the starting intro and go right to the keep with your faction choice.

**Comment by obotai** [comment]
Oh, good to know. Thanks for the tip. I will try right away.

**Comment by GreatPadinski** [comment]
Yeah it was super hard to see originally. I made the dragon bigger in 1.0.2 if you want to update the modlist quick and try again.

**Comment by GreatPadinski** [comment]
Hmm, did you talk to the innkeeper first and pick the option that mentions "start intro" or something like that? I can't remember if the statue appears before or after talking to her.

**Comment by obotai** [comment]
Yes, I did exactly as if I were doing the intro (with the specific dialogue entry to start amain quest), then I go to sleep 1 hour in the room, Sunhelm gets activated, when I wake up I see the kid and his dad talking about the imperial carriages coming, but instead of going out by the main door, I used the basement outway to go through the ladder as you suggested.

**Comment by obotai** [comment]
let me check.

**Comment by GreatPadinski** [comment]
This is what it looks like: 
![image](https://user-images.githubusercontent.com/96201854/182178380-14d80832-89c8-4d26-81a7-b3f64c8f2d96.png)

**Comment by GreatPadinski** [comment]
This is what it looks like:
![Screenshot460](https://user-images.githubusercontent.com/96201854/182178568-842073b2-f7c2-41e6-9d76-22a0670e6baa.png)

**Comment by GreatPadinski** [comment]
Yup, I just tested and if you talk to the innkeeper and sleep, it disappears. I'll update the instructions. Thanks for your patience!
