### ISSUE TITLE
Breezehome CTD

### ISSUE THREAD

**Issue by obotai** [Lost-Outpost/lost-legacy#37]
Hello Again

I have a CTD any time I try to enter Breezehome.
I suppose it's a LUX related issue. 
I activated the "LostLegacy_Lux-Crash-Fixes", but no change.
I have actually a lot of CTD when I enter some buildings, (like Blue Palace or Warmaidens), but it's randome. For breezehome it's everytime I try to enter.

**Comment by GreatPadinski** [comment]
More Lux crash fixes will be included in the next update which should be out this week. In the meantime, you can install this mod which should take care of Breezehome. Just make sure to stick it at the bottom of the left side in mo2 so it overwrites the existing file.
[LostLegacy_Lux-BreezehomeCrashFix.zip](https://github.com/Lost-Outpost/lost-legacy/files/9337776/LostLegacy_Lux-BreezehomeCrashFix.zip)

**Comment by obotai** [comment]
Ok, I will try that. Thanks.

**Comment by obotai** [comment]
Ok, it worked. Thanks.

**Comment by GreatPadinski** [comment]
Nice
