### ISSUE TITLE
Skyrim, alduins wall dragon fight ctd.

### ISSUE THREAD

**Issue by AnxietGame** [Lost-Outpost/lost-legacy#38]
[Crash_2022_8_17_5-1-16.txt](https://github.com/Lost-Outpost/lost-legacy/files/9358180/Crash_2022_8_17_5-1-16.txt)

**Comment by GreatPadinski** [comment]
Wondersofweather and Dragon mound crash. I'm replacing that feature with Splashes of Storm in 1.0.4 so the issue will be resolved then 👍

**Comment by AnxietGame** [comment]
Damn, You are on top of you're game, it's nice to see that. I'm really enjoying you're mod list, the most amount of mods I ever installed was 200 and it took forever. We really enjoy the amount of effort and passion you have put into this project to share with everyone, thank you and cheers mate.
