### ISSUE TITLE
Purchasing, decorating then entering breezyhome with lydia ctd

### ISSUE THREAD

**Issue by AnxietGame** [Lost-Outpost/lost-legacy#40]
[Crash_2022_8_21_0-32-43.txt](https://github.com/Lost-Outpost/lost-legacy/files/9388433/Crash_2022_8_21_0-32-43.txt)

**Comment by GreatPadinski** [comment]
Already fixed in 1.0.4, should be released in the next day or two.

**Comment by AnxietGame** [comment]
Sweet, Can't wait! Really like this modlist!
