### ISSUE TITLE
Rigmor of Bruma issues.

### ISSUE THREAD

**Issue by obotai** [Lost-Outpost/lost-legacy#42]
Hello again.

So, I've tried to follow the quest including Rigmor story, but it's so buggy, inconsistent, you miss triggers all the time, anytime you mingle with another quest, you have to give up right away n because it messes up with Rigmor triggers. 
I've been stuck (and force to SetStage on the console) in all the quest until quest 3, and then I gave up.

Honnestly, I'm not sure this Quest is worth it considering the issues it brings.

**Comment by GreatPadinski** [comment]
Funny you mention that, I plan on removing Rigmor in version 1.1.0 :)

**Comment by obotai** [comment]
Yea, really make sense.

By the, way I couldn't access to the Discord site, so even if this is not the normal place to do it i wanted to give you a feedback: I think you did a really great job with this list. 
Only a few minor suggestions that might improve it even more:
- Acquisitive soul Gems (really a pain to have a skeever soul stored in grand soul gems)
- No LockPick Activate (I tried to add it but for some reason, it was not compatible with papyrus version, I believe, but it helps a lot immersion)
- Disarming traps is dangerous (So that lockpincking skill is really important to handle traps), and traps get really more dangerous.

Also, I think sneak is way too powerful. I tried to add Realistic AI detection, it's a bit better, but I'm still working to know what version fits the best with the difficulty level of your list.

Of course, this is related to my own taste.

Anyway, thanks for your work on this list.

**Comment by GreatPadinski** [comment]
Thanks! I plan on adding something in 1.1.0 to resolve the soul gem issue. The other two I probably won't bother with, especially Sneak as I'm okay with it being OP since this is a power fantasy list. I appreciate the feedback though!
