### ISSUE TITLE
jorrvaskr living quarters Farkas room

### ISSUE THREAD

**Issue by oxarenaxo** [Lost-Outpost/lost-legacy#44]
when you try to enter jorrvaskr living quarters in whiterun and get to Farkas room on the right side of the corridor, you get a bug i think that shout you to death, i was lvl 1 so not sure how much dmg that was, i quick loaded the game and typed tim command so i can endure the dmg, then after i got shouted, nothing happened again after that.

also farkas doesn't seem to enter his room, but that part i am not sure about if it is a bug or vanilla.

**Comment by oxarenaxo** [comment]
![اااا](https://user-images.githubusercontent.com/113513593/191595715-8da3bf9a-75af-4408-9335-43dfc5b94f62.PNG)

**Comment by GreatPadinski** [comment]
So you're saying when you walk into Farkas' room, you randomly get shouted to death? That's definitely bizarre lol. I'll head in there next time I'm in game and see if I can reproduce the issue.

**Comment by oxarenaxo** [comment]
not inside but to the right corridor heading there

**Comment by GreatPadinski** [comment]
Tested on my 1.1.0 build and I do not experience this issue so I think we're good now.
