### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ameno-Sagiri** [Lost-Outpost/lost-legacy#45]
Running an almost unchanged version of the modpack as installed by Wabbajack. The only thing I've disabled (before even starting) were a few of the joke mods, as I've seen them already in a previous playthrough.

I was in the store called Elgrim's Elixirs under Riften, which is an alchemy shop. I was in there for awhile stealing stuff and buying/making things. At one point I waited to pass time by a few hours, and found both the shopkeeper and his wife standing in front of me staring, then the game instantly crashed. I tried to re-produce it twice and couldn't make it happen again. Seems to have something to do with the NPC called Elgrim? Might be more relevant to the developer of Elgrim's Elixirs, but there are so many patches I'm not sure who to inform of this. Here's the relevant crash log that was generated:
[Crash_2022_9_23_11-25-33.txt](https://github.com/Lost-Outpost/lost-legacy/files/9635504/Crash_2022_9_23_11-25-33.txt)

I just wanted to mention, this is the first crash in I think 32 hours of playing on this save, and it seems to be specific to this modded shop, so it might not be a serious issue.

**Comment by GreatPadinski** [comment]
Yeah if it was just a one time crash that you can't repeat, I wouldn't worry about it. Nothing really stands out to me in that crashlog anyway. Thanks!
