### ISSUE TITLE
Trouble in the install.

### ISSUE THREAD

**Issue by TheLGD27** [Lost-Outpost/lost-legacy#46]
Before i start yes ive restarted wabbajack.it solved the original issues of mods saying they cant download. Wabbajack said SkyrimSE.exe couldnt be found. I have the game and reinstalled it before the process bcs it was stated in the guide. Should i reinstall it? something weird is the log says it can open the registry for the game. its looking in an epic games folder.
[Wabbajack.current.log](https://github.com/Lost-Outpost/lost-legacy/files/9639782/Wabbajack.current.log)

**Comment by TheLGD27** [comment]
i also cant access the discord it says my inv is invalid

**Comment by oxarenaxo** [comment]
hi, try this, it's the most common why i download these modlist

just in case try uninstalling skyrim then and delete document (doc/games/skyrim se) folder then reinstalling skyrim it again , after that open the game set the settings, then close the game and see if you need the downgrade and what version you need (in the pinned comment inside discord mod support) , make sure you don't use vpn on wabbajack v2.5.3.28 , make sure you use network workaround if you need (if error happen a lot , try turn it on and off until it works -that works for me dont know why), wait the download to end after section (8/22) if all mods are downloaded perfectly then your done

**Comment by oxarenaxo** [comment]
hi, try this, it's the most common why i download these modlist

just in case try uninstalling skyrim then and delete document (doc/games/skyrim se) folder, then reinstalling skyrim it again , after that open the game settings, then close the game and see if you need the downgrade and what version you need (in the pinned comment inside discord mod support) , make sure you don't use vpn on wabbajack v2.5.3.28 , make sure you use network workaround if you need (if error happen a lot , try to turn it on and off until it works -that works for me dont know why), wait the download to end, after section (8/22) if all mods are downloaded perfectly then your done.

**Comment by oxarenaxo** [comment]
hi, try this, it's the most common way i download these modlist

just in case try uninstalling skyrim then and delete document (doc/games/skyrim se) folder, then reinstalling skyrim it again , after that open the game settings, then close the game and see if you need the downgrade and what version you need (in the pinned comment inside discord mod support) , make sure you don't use vpn on wabbajack v2.5.3.28 , make sure you use network workaround if you need (if error happen a lot , try to turn it on and off until it works -that works for me dont know why), wait the download to end, after section (8/22) if all mods are downloaded perfectly then your done.

**Comment by oxarenaxo** [comment]
hi, try this, it's the most common way i download these modlist

just in case try uninstalling skyrim then and delete document (doc/games/skyrim se) folder, then reinstalling skyrim it again , after that open the game settings, then close the game and see if you need the downgrade and what version you need (in the pinned comment inside discord mod support) , make sure you don't use vpn on wabbajack v2.5.3.28 , make sure you use network workaround if you need (if error happen a lot , try to turn it on and off until it works -that works for me dont know why), wait the download to end, after section (8/22) if all mods are downloaded perfectly then your done.

in genral you need a new clean skyrim se & the right version of skyrim.
