### ISSUE TITLE
crashes randomly

### ISSUE THREAD

**Issue by brieflywriting** [Lost-Outpost/lost-legacy#47]
it crashed, as I assume, when loading new areas. Including buildings or just chunks of soil. I think it is somewhat connected with memory and pagefile size. 
Nvidia Geforce 2060 Max-q
16 Ram
core i5-10300h 2.4 ghz

**Comment by GreatPadinski** [comment]
Increase pagefile to 20GB-30GB and see if that takes care of it. If not, please post a crashlog from inside your 'Overwrite\NetScriptFramework' folder.

**Comment by aegis1020** [comment]
I have the same issue. Random crashes when wandering outside or loading new areas. It typically happens after a certain time in game.
I increased the pagefile to 25.000 - 30.000MB on my 500GB SSD. The OS and the game are installed on it.

- Intel Core i7-3820 3.60GHz
- Nvidia Geforce GTX 960 4GB (12GB shared memory)
- Ram 16GB

Here is the crashlog : [Crash_2022_10_3_22-58-44.txt](https://github.com/Lost-Outpost/lost-legacy/files/9703946/Crash_2022_10_3_22-58-44.txt)
