### ISSUE TITLE
Can't Complete Character Creation

### ISSUE THREAD

**Issue by HelpaMePlease** [Lost-Outpost/lost-legacy#48]
Hi, I apologize if this is something others already know about. I haven't run a Wabbajack setup since before the anniversary edition update. 

Basically, I ran the downgrader to the correct skyrim version and installed the mod pack through Wabbajack like I normally would. However, I can't get past the character creation screen now to actually play. Both the 'R' key and clicking 'Done' with the mouse do nothing. Every other key and function seems to work other than that. 

I've done limited research, but I don't feel comfortable changing around anything in registry or trying to disable mods in a pack like this. Do you have a recommended fix?

**Comment by GreatPadinski** [comment]
Install this mod: https://www.nexusmods.com/skyrimspecialedition/mods/26680?tab=files

**Comment by HelpaMePlease** [comment]
Thank you for the quick fix, worked like a charm.

I appreciate all the work you've put into reviving the QWEST experience, and I look forward to putting some hours into it. Thanks again.
