### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by GeoffGUK** [Lost-Outpost/lost-legacy#49]
Wabbajack is hanging with the message
could not find a part of the path 'F\Lost Legacy\profiles\profiles'
Has anybody got a solution please?

**Comment by GreatPadinski** [comment]
Bug with wabbajack 3.0.1.6, use 3.0.1.5 for now https://github.com/wabbajack-tools/wabbajack/releases/download/3.0.1.5/3.0.1.5.zip

**Comment by GeoffGUK** [comment]
Thank you.
