### ISSUE TITLE
Horse doesn't return to me

### ISSUE THREAD

**Issue by Quietbeat** [Lost-Outpost/lost-legacy#50]
I purchased a horse which I rode for a while then I dismounted and got into a fight. The horse left and never returned. I pressed the H key and got the message that the Horse will Follow but after 10 minutes, it never did. As this mod doesn't have any option to transfer the horse to me, I'd recommend removing this mod and replacing it with Convenient Horses. I've used this mod for years and it never fails.

**Comment by GreatPadinski** [comment]
I'll make a note to check it out, but it won't be in for 1.1.0 at least.
