### ISSUE TITLE
Ultrawide monitor support

### ISSUE THREAD

**Issue by Quietbeat** [Lost-Outpost/lost-legacy#51]
I've reviewed the Discord notes and pinned messages about Ultrawide monitor support. Knowing that no one there has this type of monitor, I talked to GP about installing the following mods which all work for me. The order I have them listed is also important as otherwise you'll get an error message when opening any menu.

Two items that I'm not able to figure out are :

1. Without the following mods and clicking TAB, a menu option called Custom ???? is displayed but with the mods, this 5th menu item isn't shown.
2. On the Perk page, when hovering over a perk, the description isn't displayed next to the node.
3. When I bring up the Magic page and move the mouse over a spell, the spell information appears on the far right and the spell background appears in the middle.
![20220929075308_1](https://user-images.githubusercontent.com/57841662/193066450-9d40bc07-61be-40d0-9d4c-a5ab94d7d5fe.jpg)

**Installed mods:**
1. Nordic ui 32 by 9
4. ULTRAWIDE 3840x1080 UI FIX MAIN FILES (LOOSE)
5. SkyUI 5.2 UI Patch for ULTRAWIDE 3840x1080
6. SkyUI - Better Favorites Menu 1.0 Patch for ULTRAWIDE 3840x1080
7. SkyHud v090B UI Patch for ULTRAWIDE
8. Wider MCM Menu 1.2 Patch for ULTRAWIDE
9. UIExtensions v1-2-0 UI Patch for ULTRAWIDE
10. Experience 1.2 Patch for ULTRAWIDE
11. Clean Menu Plus 1.0 Patch for ULTRAWIDE

**Comment by GreatPadinski** [comment]
1.1.0 will include some ultrawide support (which needs testing)
