### ISSUE TITLE
Skyrim paper map broken

### ISSUE THREAD

**Issue by Mell-Moonstone** [Lost-Outpost/lost-legacy#52]
When traveling between the Falskaar map to Skyrim the paper map mod breaks and shows nothing. Help?
![20221007232349_1](https://user-images.githubusercontent.com/115332827/194686328-b9efd398-9822-4733-9089-9ad6fdcb086b.jpg)

**Comment by GreatPadinski** [comment]
I've tested going between Falskaar and Skyrim and don't run into this issue. Have you added any mods?

**Comment by Mell-Moonstone** [comment]
Yeah I have downloaded a few but I would' t think they'd break anything. I'll attach what I installed. 
![IMG_E2245](https://user-images.githubusercontent.com/115332827/194690303-e4edccfa-5177-4508-99a1-47ec8f4a5ba0.JPG)

**Comment by GreatPadinski** [comment]
Yeah that's quite a few lol. Any added plugins need to load above the map plugins (right side of mo2). I'd personally slide them above dyndolod and Lux too. But for any further questions/issues, please refer to the lost-legacy-modifications channel in the discord https://discord.gg/WF66mMu

**Comment by Mell-Moonstone** [comment]
Okay I'll do that and see what happens. Thank you for your help :)
