### ISSUE TITLE
Improved Traps Dangerous Edition + Vanilla Intro

### ISSUE THREAD

**Issue by Sparkrdom** [Lost-Outpost/lost-legacy#53]
When doing the vanilla intro, Improved Traps affects the damage of the fires in Helgen - this is especially an issue when jumping into the Inn from the tower, as the fire does 4x more damage, often outright killing characters. Then you have to re-watch the entire execution scene again. I've watched it about 20 times now. While my example below may not be the specific fires I am dying to, it does show that the Improved Traps is affecting the Helgen intro. 

The picture below shows a temporary placement of dunCGFireDamageTriggerBox in Helgen.

![Fire Damage 1](https://user-images.githubusercontent.com/22569083/196005114-469ddd43-d699-45b4-b39d-367c971f8b26.png)

In fact, there are 16 such placements in Helgen

![Fire Damage 2](https://user-images.githubusercontent.com/22569083/196005294-b2f0e2d5-46fc-4575-80d4-5def0ecfc90d.png)

dunCGFireDamageTriggerBox then refers to dunCGTrapFireTriggerExplosion01

![image](https://user-images.githubusercontent.com/22569083/196005335-0f9ac008-5dbb-4b81-b9f4-2bd11f3d6728.png)

Which calls upon dunCGTrapFireTriggerEnch01

![image](https://user-images.githubusercontent.com/22569083/196005374-6588b05c-99b2-4423-8840-710e120d6029.png)

And Improved Traps increases the magnitude of that by 4x

![image](https://user-images.githubusercontent.com/22569083/196005408-12251273-ab70-4202-88e1-719987f6cb9c.png)

This looks to be rather complicated to just "fix". 

It looks like may have been addressed in the base edition of the mod, but I suspect the Dangerous Edition is too much,
![image](https://user-images.githubusercontent.com/22569083/196005665-80da56a5-a2f2-481f-8496-46763f7f174f.png)

**Comment by GreatPadinski** [comment]
Made a patch to disable all the FireDamageTriggerBox records in Helgen
