### ISSUE TITLE
Unable to download Skyland AIO

### ISSUE THREAD

**Issue by PurplePinetree** [Lost-Outpost/lost-legacy#55]
I've been messing around with this for a while now, and haven't got it working, but I think I might know what happening. Skyland AIO was updated Oct. 22, and the file that Lost Legacy uses is no longer available for download. That said, I'm a total dunce when it comes to mods, so I could be totally wrong.
![2022-10-23](https://user-images.githubusercontent.com/116533166/197437482-cd2c7002-a97f-4904-b1f3-6482f61f46d8.png)

**Comment by silverspell03** [comment]
same here, the file is no longer downloadable

**Comment by GreatPadinski** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/34179?tab=files&file_id=235560

**Comment by silverspell03** [comment]
I already tried this link but when I try to download it, it says that the source file could not be read. Seems like a server issue
![image](https://user-images.githubusercontent.com/61562267/197830304-d4294b64-f024-4032-a9f7-d67427a019b8.png)
