### ISSUE TITLE
Unable to download skyrim_default.ini

### ISSUE THREAD

**Issue by pudy248** [Lost-Outpost/lost-legacy#56]
I can only imagine the hashes don't match, which means my default ini settings are somehow different from the pack's. I tried verifying through steam and manually changing the language to English, but no dice. If you have a copy of the ini file that matches the hash, it would be very much appreciated.

**Comment by GreatPadinski** [comment]
Try launching the game through steam once after verifying game files.

**Comment by pudy248** [comment]
I launched the game after verifying, and also tried deleting the file and then launching the game since someone said that would regenerate it (it didn't).  Even after setting the language to English in steam, the language field in the file says RUSSIAN though, so that might be related

**Comment by pudy248** [comment]
I changed the language to Spanish and then back to English in Steam and it somehow fixed it. There might have been an odd error with Steam switching languages.
