### ISSUE TITLE
refr handle count issues

### ISSUE THREAD

**Issue by GeorgesLorre** [Lost-Outpost/lost-legacy#57]
I have been playing this modpack for about 15 hours now and it has been great fun but I'm running into severe issues:

When I load saves I get warnings about `your active refr handle count is currently ....... which is dangerously close to the limit` (see screenshot). If I keep playing my later saves just don't load anymore and I get CTD, I guess the count went over the limit.

<img width="331" alt="Schermafbeelding 2022-10-28 180300" src="https://user-images.githubusercontent.com/35808396/198901378-06a0371c-a27a-4c1f-ad91-c73b5c68a300.png">

This is one of my crash reports:
[Crash_2022_10_28_0-50-19.txt](https://github.com/Lost-Outpost/lost-legacy/files/9896834/Crash_2022_10_28_0-50-19.txt)

So I searched around about this refr handle count and here is what I tried:
- I tried loading back to older saves which works but then again after a while I get the same issues
- I tired to just standing still for 1 hour (real-time not an in-game hour), save and reload. I start to then get the warnings with increasing numbers until the game breaks again.
- I tried using [resaver](https://www.nexusmods.com/skyrimspecialedition/mods/5031/) to clean my save which removed some unattached instances but did not fix the problem.
- I used SSEEdit to run the "count_loaded_refs_in_load_order" script an got the following result: `Found 587989 temporary and 207279 persistent loaded references, for a grand total of 795268 loaded references.` which is way different then my ingame number (I understand that by playing the game you add more but I have a feeling something else is wrong here)
- I tried reinstalling lost-legacy via wabbajack with the same result (I have no extra mods of my own)
- These problems started popping up after I started the main quest (talking to the messenger) but I'm not sure this is related.

I guess something is generating a lot of reference handlers even without really playing the game which eventually bricks the game. I have no idea on how to further debug this and fear my character is lost and I'm reluctant to start a new char if these problems could happen.

**Comment by GreatPadinski** [comment]
Have you added any mods? You're the first person to hit 1mil, and I know of several people with over 150 hours in the list without issue... But for the next big update, 1.1.0 which is releasing very soon, I have trimmed down the ref count a bit which should help (for a new save). But if mods were added to the list, then that could certainly be a contributing factor.

**Comment by GeorgesLorre** [comment]
@GreatPadinski I have no additional mods of my own. I really believe it is a bug where something is just continuously adding references making my playthrough a ticking time bomb.

**Comment by GreatPadinski** [comment]
Can you please post your save file? I'll check it out!

**Comment by GeorgesLorre** [comment]
[Save121_E256441D_0_42616C7468617A6172_Tamriel_001716_20221027222250_12_1.zip](https://github.com/Lost-Outpost/lost-legacy/files/9924360/Save121_E256441D_0_42616C7468617A6172_Tamriel_001716_20221027222250_12_1.zip)
