### ISSUE TITLE
Confict Between the Wayshrines Immersive Fast Travel mod and The Dark Brotherhood of Old

### ISSUE THREAD

**Issue by LBCunningham** [Lost-Outpost/lost-legacy#58]
Skyrim Wayshrines - Immersive Fast Travel - Swift SE has a conflict with The Dark Brotherhood of Old. the haafingar wayshrine is inside of Amatius Manor. I apologize that I did not take a screenshot before I disabled the wayshrines mod. I've also installed UNP, Alduin's Imprefvicticious and Chapper's Demonic Retexture mashup, Pandorable's Serana, and Arvak Replace SE on top of the pack.

**Comment by Sixdd6** [comment]
I've seen the same issue without any additional mods so it's not that.

**Comment by GreatPadinski** [comment]
Fixed in 1.1.0, thanks!
