### ISSUE TITLE
Disabling fast travel in Sunhelm doesn't work

### ISSUE THREAD

**Issue by TheStrikerFalcon** [Lost-Outpost/lost-legacy#61]
Exactly that

**Comment by MrSwordCZE** [comment]
Same for disabling eating and drinking animations

(version 1.1.0)

**Comment by GreatPadinski** [comment]
The setting from Skyrim Wayshrines MCM overrides it. Gotta disable it in both. Eating and Drinking animations is its own mod, so you'd have to disable that (not sure if that would mess up your save though).
