### ISSUE TITLE
Enemies all love Miraak

### ISSUE THREAD

**Issue by MindWeb125** [Lost-Outpost/lost-legacy#62]
Haven't made any changes from the base modpack except for adding Smooth Magic Casting Animation (https://www.nexusmods.com/skyrimspecialedition/mods/45799).

For some reason with General Subtitles enabled many enemies will have quotes from Miraak cultists. This so far has included wolves, bandits and trolls.

**Comment by GreatPadinski** [comment]
Mod update fixed this, will be in 1.1.2.
