### ISSUE TITLE
i am swimming instead of walking indoors

### ISSUE THREAD

**Issue by sorenvalen** [Lost-Outpost/lost-legacy#65]
my chacater is swimming instade of walking in doors is this something i need to rerun my wabbjack modlist to fix or is it something that can be recated no wonder i could not walk thought doors with m high elf for many hours  i porb never noticed because i like frist person view i cant drag the save data in the thing form here to give you or i would sadly we dont supprot that file type try again let me know how i can contact you to give you the saves to put into skyrim

**Comment by GreatPadinski** [comment]
Kill your character to see if that takes care of it, otherwise just load an older save.
