### ISSUE TITLE
pepe form the viglent mod wont speak to me

### ISSUE THREAD

**Issue by sorenvalen** [Lost-Outpost/lost-legacy#67]
pepe form the viglant mod wont speak to my palyer chacacater he stands at a alter and does nouthing i have reloaded a save form before i even did the last cursed spring the one of evny and i and re did the juillus fight 6 times to see if the script never fired correctly and hung but i am not even convenced it even trying to 6 six failed attpents later

**Comment by sorenvalen** [comment]
it baseing hard locks you in the watterfornt dirsctit waht going on no npc will talk to me

**Comment by GreatPadinski** [comment]
You can just use console commands to advance the scene, check the mod page.

**Comment by sorenvalen** [comment]
once you go into the aera vigalce though the portal the quest does not pop at all i have no quest to consoule advance to begain with so i am at a lost of waht to do next i also cant get picture because the mod lsit is saving them somewhere i cant find i would have to go though eveyr folder to find the pictures and cant jsut rpint screen and paste here i need to find the exacte fodler lose keeps throiwng my screenshots all 500 of them into
