### ISSUE TITLE
Trespassing everywhere where it's possible

### ISSUE THREAD

**Issue by MrSwordCZE** [Lost-Outpost/lost-legacy#69]
Hi,
I just noticed that I'm trespassing everywhere where it's possible to be trespassing. All of citizen houses at night, but also my own houses, dragonborn museum (from TOTD), thieves guild, and so on. I've been playing quite a while before I noticed this (like five days in real time) so just waiting did not help. I've track down two save files. First (421) where this is yet not happening and the second (422) where I'm trespassing everywhere. I'm also attaching my latest save (544), but I don't think it's going provide any useful information. I'm not sure what happened between saves 421 and 422. But from completed quests it seems like not too much.
I started my save at version 1.1.0 but updated to 1.1.1 in the middle of my playthrough (long before this bug started occurring).
Probably the best thing to do now is to roll back to save 421 and lose some progress. But I was wandering if somebody with more understanding of the game could find a fix to this bug.
I tried to upload my saves directly to this message, but it's too big, so I'm sending MEGA link to it.
https://mega.nz/file/jKIhCbLL#AOx4RfihImpSxgKqn5DjMT-Z4oFLvAGmOvgA2JPvk4E

**Comment by MrSwordCZE** [comment]
Also I forgot to mention that I'm playing on potato mode and tuned off mod that guards into sweetrolls and changed from quickloot RE to quickloot EE

**Comment by sirkibblesnbits** [comment]
I also have this issue, I also turned off the sweetrolls mod, but didn't change the quickloot.

**Comment by jameskirsch** [comment]
I had this exact same problem and had to restart, couldn't find a way to work around it
