### ISSUE TITLE
A posing after power attacks(?)

### ISSUE THREAD

**Issue by OOHMEGANFOX** [Lost-Outpost/lost-legacy#70]
NPCs and myself are all getting stuck A posing during combat. I'm not sure what causes it, sometimes it power attacks and sometimes it happens on light attacks too. Only happens to me in third person though, I can be stuck in third person but fully mobile in first person.

**Comment by GreatPadinski** [comment]
Have you added any mods? I haven't ran into animation issues like that, unless you maybe got into combat immediately after loading the game.
