### ISSUE TITLE
Error during install of Lost Legacy on Wabbajack 

### ISSUE THREAD

**Issue by MeriusTz** [Lost-Outpost/lost-legacy#71]
Hello ! 
All is in the title, im stuck in a error when installin the modpack with wabbajack.
Hope you can help me resolve this issue :/
Here is wabbajack log :
[Wabbajack.30.log](https://github.com/Lost-Outpost/lost-legacy/files/10251610/Wabbajack.30.log)

**Comment by GreatPadinski** [comment]
Hey sorry I don't check github often. I'm guessing you probably got it figured out now, but it looks like some of the nexus mods just failed to download. If you're still having issues, let me know!
