### ISSUE TITLE
Not a bug, but strong suggestions:

### ISSUE THREAD

**Issue by TheStrikerFalcon** [Lost-Outpost/lost-legacy#73]
1. Save System Overhaul 2 - Safe system saving regularly, smoother gameplay as a result
2. Heart Breaker - Allows you to kill essential npcs whenever you want
3. Destroy the Thieves Guild - Allows a complete alternate questline to the Thieves Guild, much like the Penitus Oculatus quest

**Comment by TheStrikerFalcon** [comment]
Other suggestions:
1. Auto Input Switch
2. Thieves Guild reform (part of Thieves Guild Requirements) or Thieves Guild for Good Guys

**Comment by TheStrikerFalcon** [comment]
Can you also add
https://www.nexusmods.com/skyrimspecialedition/mods/38670

**Comment by TheStrikerFalcon** [comment]
I also reccommend BUVARP (barely used vanilla actors something something). It gives alternative ways of dealing with some NPCs. For example, you can save Brother Tolan before he goes to Dimhollow Crypt.

**Comment by GreatPadinski** [comment]
I'll check them out!
