### ISSUE TITLE
Can you please destroy level scaling? It ruins the game.

### ISSUE THREAD

**Issue by TheStrikerFalcon** [Lost-Outpost/lost-legacy#74]
There's no point in levelling up, getting new gear and becoming more powerful if your enemies magically turn into absolute tanks for absolutely zero reason despite being locked away in a crypt for thousands of years..

**Comment by MrSwordCZE** [comment]
In this modpack, on novice difficulty, you destroy everyone one-hit, but on apprentice every enemy is like its own bossfight...
