### ISSUE TITLE
Framerate issue

### ISSUE THREAD

**Issue by TheStrikerFalcon** [Lost-Outpost/lost-legacy#75]
Game framerate starts out fine, but gets progressively slower with progress, even on Performance mode with my RTX 3060

**Comment by TheStrikerFalcon** [comment]
I'm on a PC with RTX 3060 and I use a 4k TV screen. When I switch to potato mode, my eyes feel like they're on fire from the low resolution. Could you make a faster mode that doesn't require making the game really low pixels?

**Comment by GreatPadinski** [comment]
Are you playing the game in 4k resolution then? That would definitely be your problem. And I already made several performance options available, I unfortunately don't have the time to make and maintain even more as they become exponentially more time consuming.

**Comment by TheStrikerFalcon** [comment]
> 

The 4k resolution has never been an issue on any other game
