### ISSUE TITLE
Dawnguard Dlc screen will not fade to black to turn character to vampire lord

### ISSUE THREAD

**Issue by sendnukes** [Lost-Outpost/lost-legacy#76]
Playing stock lost legacy with all combat and hardcore optionals enabled. I reached the part of the dawnguard dlc where the player is given the choice to accept harkons gift or not in the main hall. Harkon asks the question, I answer yes, he tells me to stay still and where the screen should fade to black and tp to the vampire lord tutorial room harkon just stands still not doing anything. Attempted reloading, exiting to desktop and loading, unlocking the main doors and leaving and re-entering to try to reset the quest and no success. And the issue is i cannot just advance the quest as i wont receive vampire lord powers. I found some results on google but the only definitive cause was custom female animations. My character is female however if thats relevant possibly.

**Comment by GreatPadinski** [comment]
Switched to Better Vampires in 1.2, should be resolved
