### ISSUE TITLE
Character stuck after attacking things like walls or shields

### ISSUE THREAD

**Issue by plattdl** [Lost-Outpost/lost-legacy#81]
Hi I think I am having the same issue as #70 which got closed. I have not added any mods but I did enable vahalla/precision in the optionals. Skyshards too but doubt that is it. Is there anything I need to do to existing mods to make those optional ones work? By the way, I did enable both patches for the respective combat mods under them.

**Comment by GreatPadinski** [comment]
Yeah I'm probably just going to remove Precision, not really a fan of the mod anyway.
