### ISSUE TITLE
well

### ISSUE THREAD

**Issue by sorenvalen** [Lost-Outpost/lost-legacy#82]
i laoded a save 10 hour away form the save i i had the failed do to referce handle issue on the same in game hour as the last save my save hit the referce count issue again where i saved there was near zero chance for something to spwan again in that aera at that time but i and still having the issue in my provous issue but not matter how far back i go on the save it reaching it as long as my save follows the same path

**Comment by GreatPadinski** [comment]
Yeah probably not much you can do on that save file then unfortunately.
