### ISSUE TITLE
ya dun goofed

### ISSUE THREAD

**Issue by Drizzlee3** [Lost-Outpost/lost-legacy#83]
i got this message when loading my latest save. then racemenu pops up. but when i click done i get the message again and again. what is causing this?

**Comment by Drizzlee3** [comment]
https://ibb.co/wRvJkFZ this is a screenshot of the message

**Comment by GreatPadinski** [comment]
Can you post the image directly to github please?

**Comment by Drizzlee3** [comment]
![The-Elder-Scrolls-V-Skyrim-Special-Edition-Screenshot-2023-01-23-01-18-27-88](https://user-images.githubusercontent.com/123608411/215829683-3eb87426-8f0b-4246-a674-b7499798016b.png)

**Comment by Drizzlee3** [comment]
now i was able to walk around. but all my skillpoints were reset and i cant get rid of the message

**Comment by Drizzlee3** [comment]
the message doesnt happen when i get the message of are you sure you want to load this save because mods are missing. other saves don't give me the message and then all my perks are removed. my armor gets removed, some weird magic effect gets added and circles around me. whenever i click ok it pops up again.

**Comment by GreatPadinski** [comment]
Yeah no idea, I'd suggest reinstalling the modlist and maybe try a new save file.
