### ISSUE TITLE
Gladiator Quests and New Land/Build Mods

### ISSUE THREAD

**Issue by gigglestick90** [Lost-Outpost/lost-legacy#84]
Is it possible to add these quest and build type mods in future releases? I would love to experience these in Lost Legacy, but wasn't sure if it conflicted with other quest mods:

Gladiator Quests:
1. [Ravengate](https://www.nexusmods.com/skyrimspecialedition/mods/12617)
2. [Pit Fighter and its expansion](https://www.nexusmods.com/skyrimspecialedition/mods/22513)
3. [Dwemer Colosseum](https://www.nexusmods.com/skyrimspecialedition/mods/4435)

New Lands+Builds:
1. [Phenderix Magic World](https://www.nexusmods.com/skyrimspecialedition/mods/6551)
2. [Phenderix Arcane Brawler](https://www.nexusmods.com/skyrimspecialedition/mods/64976)
3. [Phenderix Arcane Arsenal](https://www.nexusmods.com/skyrimspecialedition/mods/64696)
4. [Phenderix Magic SPID - Spells for NPCs](https://www.nexusmods.com/skyrimspecialedition/mods/64705)

**Comment by GreatPadinski** [comment]
I've got Pit Fighter on my list to look into adding for the next version, not really interested in the other 2 though. And I've tested the Phenderix mods in the past but not interested in adding them.
