### ISSUE TITLE
Missing support for 32:9.

### ISSUE THREAD

**Issue by VulpixAtAlola** [Lost-Outpost/lost-legacy#89]
21:9 support does not work for 32:9 monitors. However theres an easy solution to this because nordic UI does have a 32:9 patch, I would suggest including both 32:9 and 21:9 support mods in the optional ultrawide and superultrawide tab. I got my game working on 32:9 by installing said mod (however i messed up first and lost the GUI tab to custom skills. I can still use the hotkey...)

**Comment by GreatPadinski** [comment]
Will include it in 1.2.0, thanks!
