### ISSUE TITLE
Inigo horse riding bug (has a patch now?)

### ISSUE THREAD

**Issue by Veronica-White** [Lost-Outpost/lost-legacy#90]
Inigo has a bug where if you take anything from his starting inventory while RaceMenu and SKSE64 are installed, he can't ride horses anymore. There's a patch for it here: https://www.nexusmods.com/skyrimspecialedition/mods/62868

the patch author is hoping to have it integrated in the next update of Inigo but it would be a good idea to have it in the modlist if you have to time to add it. 

Thank you!

**Comment by GreatPadinski** [comment]
Will be included in 1.2.0, thanks!
