### ISSUE TITLE
window goes into a resolution FAR beyond my screens

### ISSUE THREAD

**Issue by Lobituki** [Lost-Outpost/lost-legacy#92]
so when i try to load the modpack, the game will open *normally* for about 1 minute before becoming the corner of the game. . . idek man. idk what's happening, why it's doing this or anything.. also, i've tried to mess with the resolution in the launcher file in Stock Game, but it doesn't do anything. i'm not sure if it's one of the mods or not, but if it is please tell me what it is (i have none of the ultrawide options enabled) 
![image](https://user-images.githubusercontent.com/61525238/226840023-41b486e8-ce90-409d-bec1-16ff3ddb3da5.png)

**Comment by Lobituki** [comment]
i've even tried to mess with the properties of the game itself, doesn't work

**Comment by from-ashes** [comment]
> i've even tried to mess with the properties of the game itself, doesn't work

This happened to me too, here's the fix. 
"Windows Scaling can prevent games displaying correctly, often resulting in appearing 'zoomed in'. To mitigate this, follow the steps outlined in the image below.

If your chosen modlist uses the Stock Game feature, you will need to apply the change to the .exe inside the "Stock Game" folder."

https://old.reddit.com/r/wabbajack/comments/tgomur/lunching_skyrim_through_mod_organizer/
![skyrim-scaling](https://user-images.githubusercontent.com/13206241/227086288-62ca64c0-fb03-4b24-8ad7-649f38e53b97.png)

**Comment by Lobituki** [comment]
thank you!! this actually worked; my mother and i were messing with it but didn't get to the high dpi settings. thanks!! <3

**Comment by Lobituki** [comment]
now idk how to close this i'm just praying this does it
