### ISSUE TITLE
unable to start 

### ISSUE THREAD

**Issue by MageHear** [Lost-Outpost/lost-legacy#94]
this may be entirely my fault but I'm unable to start lost legacy. when I attempt to start it it'll show that it starts in steam, but in a few seconds crash. I've done everything, I've downloaded net 5.0 and even tried 7.0 I've downloaded microsoft visual which was already on my pc, downloaded Skyrim se to a different folder using the tool and cleaned it as well as set up pagefile. if it helps, when I disable all mods it boots up but the skyrim symbol has no textures it's just white and what I assume to be smoke is now just black textures that will cover the white symbol. when I attempt to start the game it crashes. I've spent almost 2 weeks trying to fix this by myself but I've tried everything. did I skip a step or perhaps do one wrong? I use amd

**Comment by GreatPadinski** [comment]
Sorry for the super long delay, apparently my notifications got turned off for these... Are you still having issues?
