### ISSUE TITLE
Constant loading screen after I hit continue from the main menu

### ISSUE THREAD

**Issue by Msyed33** [Lost-Outpost/lost-legacy#96]
Hi all, I just started my play through of lost legacy and I have been enjoying it so far. Only problem is I can’t continue it. I do have the immersive music mod added to the mod list, but that’s it, so I’m not sure if that’s the thing that’s causing problems. I have also tried looking up to see if anyone else has this problem online and I only saw one suggestion which is to start from another save, which I did and still nothing. I’ve also adjusted my virtual memory, and flushed my dns and still nothing. Hope someone could help me out.

update: I also did try it without the immersive music mod with a completely new save and I’m able to do my play through up until I reach dragonsreach to first talk to the jarl and if I save in there it would still give me the same issue that I’ve been having if I try to log back in.

**Comment by GreatPadinski** [comment]
I replied to your post in discord, so closing this one here.
