### ISSUE TITLE
can't craft the daedric versions of Animated Armory weapons.

### ISSUE THREAD

**Issue by louthinator** [Lost-Outpost/lost-legacy#97]
I went to the skyforge at night, I have all smithing perks unlocked, other daedric items were available to craft but none of the Animated Armory items are. I can't find rapiers, claws, glaives, spears, nothing. Every other variant is there, it's just daedric that's missing.

**Comment by Hukkatsu** [comment]
In -lost-legacy discord chat on 5/31/23 we discovered that the black book patch is not applied to animated armory weapons yet. They still have finding the black books as a smithing requirement.

**Comment by GreatPadinski** [comment]
On the list for 1.2.1
