### ISSUE TITLE
Vulthuryol does not drop Half-digested Geary Key

### ISSUE THREAD

**Issue by Hukkatsu** [Lost-Outpost/lost-legacy#99]
Morrowloot ultimate artifact Seht's boots is unobtainable because the player has no means to obtain the Half-digested Geary Key. This key is meant to drop from Vulthuryol, the dragon in blackreach.

Editing the dragon's "Use Inventory" flag from "Use Inventory" to null in LostLegacy_MLU-DeadlyDragons.esp allows the dragon to drop the key and still retains the ability to drop his scales for LotD museum completion.

Dragon form id: 0007EAC7   EditorID: BlackreachDragon
Key form id: C505C889   EditorID: _mwl_sehtkey

My drops when testing the patch edit:
![SuccessfulTest](https://github.com/Lost-Outpost/lost-legacy/assets/135540947/24a29b6f-37ad-4da4-aa6e-1bbe5377afcb)

**Comment by GreatPadinski** [comment]
Fixed for 1.2.0, thanks!
